version: 2
jobs:
  build:
    docker:
      - image: elonafoobar/build:latest

    steps:
      - checkout

      - run:
          name: doc
          command: |
            source ~/.cargo/env && make docgen
            make ldoc

      - run:
          name: luacheck
          command: make luacheck || true
